### ISSUE TITLE
paket.exe: The request was aborted: Could not create SSL/TLS secure channel. 

### ISSUE THREAD

**Issue by mykolav** [tpetricek/elmish-spreadsheet#2]
Hi Tomas,

While executing these commands

```
yarn install              # Install JavaScript packages, you can use npm install too
dotnet restore            # Install .NET dependencies, most notably Fable
code .                    # If you're using VS Code, open it here 
cd src                    # Go to the source directory
dotnet fable yarn-start   # Run fable in the background, you can use npm-start too
```
`dotnet restore` gave me

>   The request was aborted: Could not create SSL/TLS secure channel. (Github - cached (temporarily ignore updates))
> D:\src\elmish-spreadsheet\.paket\Paket.Restore.targets(74,5): error MSB3073: The command ""D:\src\elmish-spreadsheet\.paket\paket.exe" restore" exited with code 1. [D:\src\elmish-spreadsheet\src\spreadsheet.fsproj]

To resolve the issue I copied `paket.bootstrapper.exe` into the `elmish-spreadsheet/.paket/` folder and ran it.  
The version of `paket.exe` that the bootstrapper downloaded let `dotnet restore` complete successfully.

So apparently, updating the repo's `paket.exe` should correct the issue.

Thank you!
Mykola.

**Comment by tpetricek** [comment]
Thanks for investigating! It should be possible to download the latest `paket.bootstrapper.exe` and rename it to `paket.exe` and put it to the `.paket` folder (this way, Paket will run in magic mode and download itself behind the scene). If you could check that this works and send a PR, that would be fantastic!

**Comment by mykolav** [comment]
Hi Tomas,
Here is a PR -- https://github.com/tpetricek/elmish-spreadsheet/pull/3

The PR's description says "Update version of paket.exe",
but actually I followed your suggestion and `.paket\paket.exe` is a renamed `paket.bootstrapper.exe`.

Thank you!
Mykola.

**Comment by tpetricek** [comment]
Fantastic, thank you @mykolav!
